export default [
  // Dados para Outubro 2024 (mês atual)
  {
    description: "Aluguel Outubro",
    amount: "800.00",
    type: "saída",
    frequency: "recorrente",
    date: "2024-10-01",
  },
  {
    description: "Supermercado Outubro",
    amount: "200.00",
    type: "saída",
    frequency: "eventual",
    date: "2024-10-05",
  },
  {
    description: "Energia Outubro",
    amount: "120.00",
    type: "saída",
    frequency: "recorrente",
    date: "2024-10-10",
  },
  {
    description: "Internet Outubro",
    amount: "50.00",
    type: "saída",
    frequency: "recorrente",
    date: "2024-10-15",
  },
  {
    description: "Gasolina Outubro",
    amount: "80.00",
    type: "saída",
    frequency: "eventual",
    date: "2024-10-20",
  },
  {
    description: "Livros técnicos",
    amount: "250.00",
    type: "saída",
    frequency: "eventual",
    date: "2018-03-12",
  },
  {
    description: "Curso online",
    amount: "500.00",
    type: "saída",
    frequency: "eventual",
    date: "2018-04-15",
  },
  {
    description: "Energia elétrica",
    amount: "130.50",
    type: "saída",
    frequency: "recorrente",
    date: "2018-05-10",
  },
  {
    description: "Água",
    amount: "88.00",
    type: "saída",
    frequency: "recorrente",
    date: "2018-06-15",
  },
  {
    description: "Manutenção do carro",
    amount: "450.00",
    type: "saída",
    frequency: "eventual",
    date: "2018-07-22",
  },
  {
    description: "Energia elétrica",
    amount: "110.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-02-10",
  },
  {
    description: "Academia",
    amount: "90.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-03-10",
  },
  {
    description: "Medicamentos",
    amount: "120.50",
    type: "saída",
    frequency: "eventual",
    date: "2019-03-18",
  },
  {
    description: "Cinema",
    amount: "40.00",
    type: "saída",
    frequency: "eventual",
    date: "2019-05-22",
  },
  {
    description: "Plano de Saúde",
    amount: "320.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-06-23",
  },
  {
    description: "Jantar",
    amount: "150.00",
    type: "saída",
    frequency: "eventual",
    date: "2019-07-28",
  },
  {
    description: "Energia elétrica",
    amount: "140.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-01-10",
  },
  {
    description: "Água",
    amount: "75.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-02-15",
  },
  {
    description: "Viagem",
    amount: "1200.00",
    type: "saída",
    frequency: "eventual",
    date: "2020-03-20",
  },
  {
    description: "Eletrodoméstico",
    amount: "800.00",
    type: "saída",
    frequency: "eventual",
    date: "2020-04-05",
  },
  {
    description: "Energia elétrica",
    amount: "100.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-05-10",
  },
  {
    description: "Água",
    amount: "80.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-06-15",
  },
  {
    description: "Telefone",
    amount: "110.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-07-23",
  },
  {
    description: "Plano de Saúde",
    amount: "310.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-07-23",
  },
  {
    description: "Refeição",
    amount: "30.00",
    type: "saída",
    frequency: "eventual",
    date: "2020-07-10",
  },
  {
    description: "Cafeteira nova",
    amount: "260.00",
    type: "saída",
    frequency: "eventual",
    date: "2020-07-26",
  },
  {
    description: "Cinema",
    amount: "55.00",
    type: "saída",
    frequency: "eventual",
    date: "2020-07-30",
  },
  {
    description: "Energia elétrica",
    amount: "150.55",
    type: "saída",
    frequency: "recorrente",
    date: "2019-01-10",
  },
  {
    description: "Água",
    amount: "75.55",
    type: "saída",
    frequency: "recorrente",
    date: "2019-01-15",
  },
  {
    description: "Telefone",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2019-01-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-01-23",
  },
  {
    description: "Compras do mês",
    amount: "625.78",
    type: "saída",
    frequency: "recorrente",
    date: "2018-01-23",
  },
  {
    description: "Lanche",
    amount: "45.70",
    type: "saída",
    frequency: "eventual",
    date: "2018-01-23",
  },
  {
    description: "Blusa",
    amount: "95.70",
    type: "saída",
    frequency: "eventual",
    date: "2018-01-23",
  },
  {
    description: "Energia elétrica",
    amount: "125.55",
    type: "saída",
    frequency: "recorrente",
    date: "2018-02-10",
  },
  {
    description: "Água",
    amount: "90.15",
    type: "saída",
    frequency: "recorrente",
    date: "2018-02-15",
  },
  {
    description: "Telefone",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-02-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-02-23",
  },
  {
    description: "Compras do mês",
    amount: "540.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-02-25",
  },
  {
    description: "Parcela do Celular 1/5",
    amount: "150.99",
    type: "saída",
    frequency: "eventual",
    date: "2020-02-26",
  },
  {
    description: "Cinema",
    amount: "45.00",
    type: "saída",
    frequency: "eventual",
    date: "2020-02-23",
  },
  {
    description: "Energia elétrica",
    amount: "97.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-03-10",
  },
  {
    description: "Água",
    amount: "100.10",
    type: "saída",
    frequency: "recorrente",
    date: "2020-03-15",
  },
  {
    description: "Telefone",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-03-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-03-23",
  },
  {
    description: "Compras do mês",
    amount: "800.50",
    type: "saída",
    frequency: "recorrente",
    date: "2020-03-17",
  },
  {
    description: "Parcela do Celular 2/5",
    amount: "150.99",
    type: "saída",
    frequency: "eventual",
    date: "2020-03-18",
  },
  {
    description: "Troca de Oléo do carro",
    amount: "90.00",
    type: "saída",
    frequency: "eventual",
    date: "2020-03-23",
  },
  {
    description: "Energia elétrica",
    amount: "75.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-04-10",
  },
  {
    description: "Água",
    amount: "80.33",
    type: "saída",
    frequency: "recorrente",
    date: "2020-04-15",
  },
  {
    description: "Telefone",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-04-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-04-23",
  },
  {
    description: "Compras do mês",
    amount: "600.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-04-25",
  },
  {
    description: "Parcela do Celular 3/5",
    amount: "150.99",
    type: "saída",
    frequency: "eventual",
    date: "2020-04-26",
  },
  {
    description: "Ebook de React Js",
    amount: "85.95",
    type: "saída",
    frequency: "eventual",
    date: "2020-04-13",
  },
  {
    description: "Energia elétrica",
    amount: "125.55",
    type: "saída",
    frequency: "recorrente",
    date: "2020-05-10",
  },
  {
    description: "Água",
    amount: "90.15",
    type: "saída",
    frequency: "recorrente",
    date: "2020-05-15",
  },
  {
    description: "Telefone",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-05-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-05-23",
  },
  {
    description: "Compras do mês",
    amount: "540.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-05-25",
  },
  {
    description: "Parcela do Celular 4/5",
    amount: "150.99",
    type: "saída",
    frequency: "eventual",
    date: "2020-05-26",
  },
  {
    description: "Blusa Iron Man",
    amount: "150.00",
    type: "saída",
    frequency: "eventual",
    date: "2020-01-23",
  },
  {
    description: "Energia elétrica",
    amount: "200.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-06-10",
  },
  {
    description: "Água",
    amount: "150.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-06-15",
  },
  {
    description: "Telefone",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-06-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-06-23",
  },
  {
    description: "Compras do mês",
    amount: "559.15",
    type: "saída",
    frequency: "recorrente",
    date: "2020-06-25",
  },
  {
    description: "Parcela do Celular 5/5",
    amount: "150.99",
    type: "saída",
    frequency: "eventual",
    date: "2020-06-26",
  },
  {
    description: "Perfume",
    amount: "250.00",
    type: "saída",
    frequency: "eventual",
    date: "2020-06-21",
  },
  {
    description: "Energia elétrica",
    amount: "250.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-07-10",
  },
  {
    description: "Água",
    amount: "90.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-07-15",
  },
  {
    description: "Telefone",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-07-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-07-23",
  },
  {
    description: "Compras do mês",
    amount: "700.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-07-25",
  },
  {
    description: "Cafeteira",
    amount: "250.00",
    type: "saída",
    frequency: "eventual",
    date: "2020-07-26",
  },
  {
    description: "Pizza",
    amount: "60.00",
    type: "saída",
    frequency: "eventual",
    date: "2020-07-19",
  },
];
